backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "exampleSite/static/images"
public_folder: "/static/images"


collections:

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "slug"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image Alt text", name: "imageAlt", widget: "string"}
      - {label: "Image caption", name: "imageCap", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "status"
    label: "Status"
    folder: "content/status"
    create: true
    slug: "slug"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image Alt text", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}